package models;

import android.os.Parcel;
import android.os.Parcelable;
import androidx.annotation.NonNull;
import androidx.room.Entity;
import androidx.room.PrimaryKey;

// Entity annotation defines that this class represents a SQLite table named "user"
@Entity(tableName = "user")
public class User implements Parcelable {

    // Primary key auto-generated by Room
    @PrimaryKey(autoGenerate = true)
    @NonNull
    private int userId;

    // User's name
    private String name;

    // User's email
    private String email;

    // User's password
    private String password;

    // User's phone number
    private String phone;

    // Getter and Setter methods for each property

    public int getUserId() {
        return userId;
    }

    public void setUserId(int userId) {
        this.userId = userId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    // Default constructor
    public User() {
        // Initialize properties using getters (may not be necessary)
        this.userId = getUserId();
        this.name = getName();
        this.email = getEmail();
        this.password = getPassword();
        this.phone = getPhone();
    }

    // Parcelable implementation

    // Creator field for generating instances of the User class from a Parcel
    public static final Parcelable.Creator<User> CREATOR = new Parcelable.Creator<User>() {
        public User createFromParcel(Parcel in) {
            return new User();
        }

        public User[] newArray(int size) {
            return new User[size];
        }
    };

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(@NonNull Parcel dest, int flags) {
        // Write object data to the Parcel (if needed)
    }
}
